version: v2beta1
name: account-subgraph

vars:
  IMAGE: ghcr.io/sun-asterisk-research/microservices-example/account-subgraph

pipelines:
  dev:
    run: |-
      run_dependencies --all        # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all     # 2. Ensure pull secrets
      create_deployments --all      # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev account-subgraph    # 4. Start dev mode "account-subgraph" (see "dev" section)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

images:
  account-subgraph:
    image: ${IMAGE}
    dockerfile: ./dockerfiles/prod.Dockerfile
    context: ./

deployments:
  account-subgraph:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        labels:
          app: account-subgraph
        containers:
          - image: ${IMAGE}
        service:
          ports:
            - port: 8000

dev:
  account-subgraph:
    labelSelector:
      app: account-subgraph
    devImage: ghcr.io/kimyvgy/rustdev:1.71-bullseye
    workingDir: /account-subgraph
    sync:
      - path: ./
        uploadExcludePaths:
          - target/
        startContainer: true
    command: ["./devspace_start.sh"]
    persistPaths:
      - path: ./target
      - path: /usr/include/google/
      - path: /usr/local/cargo/registry/
