apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Deployment
      name: account-service
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: account-subgraph
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: contents-view-subgraph
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: web-app
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: views-count-subgraph
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
  - target:
      kind: Deployment
      name: views-count-service
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/resources/limits
