version: v2beta1
name: microservices-example

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all          # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all       # 2. Ensure pull secrets
      build_images go-base rust-base  # 3. Build base image for go & rust
      create_deployments --all        # 4. Deploy Helm charts and manifests specfied as "deployments"
      start_dev --all                 # 5. Start dev mode "app" (see "dev" section)

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  go-base:
    image: ghcr.io/sun-asterisk-research/microservices-example/go
    dockerfile: ./docker/go.Dockerfile
    tags:
      - latest
  rust-base:
    image: ghcr.io/sun-asterisk-research/microservices-example/rust
    dockerfile: ./docker/rust.Dockerfile
    tags:
      - latest

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `kubectl` but you can also define `helm` deployments
    kubectl:
      manifests:
        - ./k8s/dev
      kustomize: true

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  account-service:
    labelSelector:
      app: account-service
    devImage: ghcr.io/sun-asterisk-research/microservices-example/go:latest
    sync:
      - path: ./src/account-service:/src
        startContainer: true
    workingDir: /src
    command: ["./devspace_start.sh"]

  account-subgraph:
    labelSelector:
      app: account-subgraph
    devImage: ghcr.io/sun-asterisk-research/microservices-example/rust:latest
    sync:
      - path: ./src/account-subgraph:/src
        startContainer: true
    workingDir: /src
    command: ["./devspace_start.sh"]

  web-app:
    labelSelector:
      app: web-app
    devImage: node:16-alpine
    sync:
      - path: ./src/web-app:/src
        startContainer: true
        uploadExcludePaths:
          - node_modules/
    workingDir: /src
    command: [ "./devspace_start.sh" ]

  contents-view-subgraph:
    labelSelector:
      app: contents-view-subgraph
    devImage: node:16-alpine
    sync:
      - path: ./src/contents-view-subgraph:/src
        startContainer: true
        excludePaths:
          - dist/
        uploadExcludePaths:
          - node_modules/
    workingDir: /src
    command: [ "./devspace_start.sh" ]

  views-count-service:
    labelSelector:
      app: views-count-service
    devImage: ghcr.io/sun-asterisk-research/microservices-example/rust:latest
    sync:
      - path: ./src/views-count-service:/src
        startContainer: true
    workingDir: /src
    command: [ "./devspace_start.sh" ]

  views-count-subgraph:
    labelSelector:
      app: views-count-subgraph
    devImage: node:16-alpine
    sync:
      - path: ./src/views-count-subgraph:/src
        startContainer: true
        uploadExcludePaths:
          - node_modules/
    workingDir: /src
    command: [ "./devspace_start.sh" ]
