query StoriesForHome($offset: Int) {
  stories {
    stories(limit: 12, offset: $offset, orderBy: {publishedAt: DESC}) {
      hashid
      title
      previewImage
      previewContent
      publishedAt
      author {
        username
        fullname
        avatar
      }
    }
  }
}
