// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SignUpRequest) Validate() error {
	if this.Fullname == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Fullname", fmt.Errorf(`value '%v' must not be an empty string`, this.Fullname))
	}
	if !(len(this.Fullname) < 255) {
		return github_com_mwitkow_go_proto_validators.FieldError("Fullname", fmt.Errorf(`value '%v' must have a length smaller than '255'`, this.Fullname))
	}
	if this.Email == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must not be an empty string`, this.Email))
	}
	if !(len(this.Email) < 255) {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must have a length smaller than '255'`, this.Email))
	}
	if this.Username == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must not be an empty string`, this.Username))
	}
	if !(len(this.Username) > 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length greater than '3'`, this.Username))
	}
	if !(len(this.Username) < 30) {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must have a length smaller than '30'`, this.Username))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	if !(len(this.Password) > 7) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length greater than '7'`, this.Password))
	}
	if !(len(this.Password) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.Password))
	}
	if this.ConfirmPassword == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ConfirmPassword", fmt.Errorf(`value '%v' must not be an empty string`, this.ConfirmPassword))
	}
	if !(len(this.ConfirmPassword) > 7) {
		return github_com_mwitkow_go_proto_validators.FieldError("ConfirmPassword", fmt.Errorf(`value '%v' must have a length greater than '7'`, this.ConfirmPassword))
	}
	if !(len(this.ConfirmPassword) < 31) {
		return github_com_mwitkow_go_proto_validators.FieldError("ConfirmPassword", fmt.Errorf(`value '%v' must have a length smaller than '31'`, this.ConfirmPassword))
	}
	return nil
}
func (this *SignUpResponse) Validate() error {
	return nil
}
func (this *GetTokenRequest) Validate() error {
	if this.Username == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must not be an empty string`, this.Username))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	return nil
}
func (this *GetTokenResponse) Validate() error {
	return nil
}
