name: account-subgraph

on:
  pull_request:
    paths:
      - .github/workflows/account-subgraph.yml
      - src/account-subgraph/**
  push:
    branches: [main]
    paths:
      - .github/workflows/account-subgraph.yml
      - src/account-subgraph/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src/account-subgraph
          file: ./src/account-subgraph/dockerfiles/prod.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/microservices-example/account-subgraph:build-${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/microservices-example/account-subgraph:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
