on:
  pull_request:
    paths:
      - .github/workflows/account-service.yml
      - src/account-service/**
  push:
    branches: [main]
    paths:
      - .github/workflows/account-service.yml
      - src/account-service/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src/account-service
          file: ./src/account-service/dockerfiles/prod.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/microservices-example/account-service:build-${{ github.run_number }}
