on:
  pull_request:
    paths:
      - 'src/contents-view-subgraph/**'
  push:
    paths:
      - 'src/contents-view-subgraph/**'

jobs:
  docker:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src/contents-view-subgraph
          file: ./src/contents-view-subgraph/dockerfiles/prod.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/microservices-example/contents-view-subgraph:build-${{ github.run_number }}
