name: Hasura
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/hasura.yml
      - src/hasura/**
jobs:
  hasura:
    name: Hasura
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Apply hasura migrations
        uses: tibotiber/hasura-action@v3.0
        with:
          args: migrate apply --all-databases
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_WORKDIR: src/hasura
          HASURA_ENGINE_VERSION: v2.33.3
      - name: Apply hasura metadata
        uses: tibotiber/hasura-action@v3.0
        with:
          args: metadata apply
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_WORKDIR: src/hasura
          HASURA_ENGINE_VERSION: v2.33.3
